---
- name: Disabling Swap
  become: true
  ansible.builtin.command: swapoff -a


- name: Disable SWAP in /etc/fstab
  become: true
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Rebooting the machine
  become: true
  reboot:
    msg: Machine repooted for applying SWAP changes
    post_reboot_delay: 5

- name: Add an apt signing key for Docker
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for stable version
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Install docker and its dependecies
  become: true
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io


- name: Add vagrant user to docker group
  become: true
  user:
    name: vagrant
    group: docker

- name: Deleting config.toml
  become: true
  ansible.builtin.file:
    path: /etc/containerd/config.toml
    state: absent


# Commented because kubeadm was not happy with it
#
# - name: Copying config.toml
#   become: true
#   ansible.builtin.copy:
#     src: config.toml
#     dest: /etc/containerd/

- name: Starting Containerd service
  become: true
  ansible.builtin.service:
    name: containerd
    state: started
    enabled: true


- name: Add an apt signing key for Kubernetes
  become: true
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding apt repository for Kubernetes
  become: true
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Install Kubernetes binaries
  become: true
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - kubelet 
      - kubeadm 
      - kubectl

- name: Restarting Containerd service
  become: true
  ansible.builtin.service:
    name: containerd
    state: restarted