---
- name: Installing Base packages needed
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - inetutils-traceroute

- name: Installing NGINX & HAProxy packages
  become: true
  apt: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - haproxy
      - nginx

- name: Allowing nginx in UFW
  become: true
  community.general.ufw:
    rule: allow
    port: 6443
    logging: on

- name: Deleting haproxy.cfg
  become: true
  ansible.builtin.file:
    path: /etc/haproxy/haproxy.cfg
    state: absent

- name: Copying haproxy.cfg
  become: true
  ansible.builtin.copy:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg

- name: Starting haproxy service
  become: true
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: true


