---
- name: Installing NGINX & HAProxy packages
  become: true
  apt: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - haproxy
      - nginx
      - rsyslog

- name: Allowing nginx in UFW
  become: true
  community.general.ufw:
    rule: allow
    port: 6443
    logging: on

- name: Deleting haproxy.cfg
  become: true
  ansible.builtin.file:
    path: /etc/haproxy/haproxy.cfg
    state: absent

- name: Copying haproxy.cfg
  become: true
  ansible.builtin.copy:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg

- name: Copying haproxy.cfg
  become: true
  ansible.builtin.copy:
    src: haproxy.conf
    dest: /etc/rsyslog.d/

- name: Enabling haproxy and associated service
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
  loop:
      - rsyslog
      - haproxy

- name: Starting haproxy and associated service
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
      - rsyslog
      - haproxy


