---
- name: Installing Base packages needed
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - inetutils-traceroute


- name: Downloading K9s on all boxes
  become: true
  ansible.builtin.unarchive:
    src: "{{ k9sversion }}"
    dest: /usr/local/bin
    remote_src: yes
    include:
      - k9s